services:
  # --- API service---
  blog_service:
    build: .
    container_name: blog_api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API__PORT:-8000}:8000"
    volumes:
      - .:/app:cached
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent --show-error http://${API__HOST}:${API__PORT}/api/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog_net
    profiles: ["default"]

  # --- Users API service ---
  users_service:
    build:
      context: ./services/users
    container_name: users_api
    env_file:
      - .env
    depends_on:
      blog_db:
        condition: service_healthy
    ports:
      - "8100:8100"
    volumes:
      - ./services/users:/app:cached
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent --show-error http://localhost:8100/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - blog_net
    profiles: ["default"]

  # --- Blog migrations service ---
  blog_migrations:
    build: .
    container_name: blog_migrations
    command: bash -c "sleep 5 && alembic upgrade head"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    networks:
      - blog_net
    profiles: ["default"]

  # --- Users migrations service ---
  users_migrations:
    build:
      context: ./services/users
    container_name: users_migrations
    command: bash -c "sleep 5 && alembic upgrade head"
    env_file:
      - .env
    depends_on:
      blog_db:
        condition: service_healthy
    restart: "no"
    networks:
      - blog_net
    profiles: ["default"]

  # --- Blog database service ---
  blog_db:
    image: postgres:17
    container_name: blog_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB__USER} -d $${DB__NAME}"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - blog_net
    profiles: ["default"]

  # --- Users database service ---
  users_db:
    image: postgres:17
    container_name: users_db
    restart: always
    environment:
      POSTGRES_DB: users_db
      POSTGRES_USER: users_admin
      POSTGRES_PASSWORD: users_password
    volumes:
      - users_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users_admin -d users_db"]
      interval: 10s
      timeout: 5s
      retries: 2
    networks:
      - blog_net
    profiles: ["default"]

  # --- Test blog database service ---
  test_blog_db:
    image: postgres:17
    container_name: blog_test_db
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["test"]

  # --- Test users database service ---
  test_users_db:
    image: postgres:17
    container_name: users_test_db
    restart: always
    environment:
      POSTGRES_DB: test_users_db
      POSTGRES_USER: users_admin
      POSTGRES_PASSWORD: users_password
    volumes:
      - test_users_postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U users_admin -d test_users_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["test"]

  # --- NGINX gateway ---
  gateway:
    image: nginx:latest
    container_name: blog_api_gateway
    ports:
      - "80:80"
    networks:
      - blog_net
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      blog_api:
        condition: service_healthy
      users_api:
        condition: service_healthy
    profiles: ["default"]

volumes:
  postgres_data:
  test_postgres_data:

networks:
  blog_net:
    driver: bridge
