services:
  # --- API Service---
  app:
    build: .
    container_name: blog_api
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "${API__PORT:-8000}:8000"
    volumes:
      - .:/app:cached
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --fail --silent --show-error http://${API__HOST}:${API__PORT}/api/health || exit 1",
        ]
      interval: 10s
      timeout: 5s
      retries: 5
    profiles: ["default"]

  # --- Migration Service ---
  migrate:
    build: .
    container_name: blog_migrate
    command: bash -c "sleep 5 && alembic upgrade head"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    restart: "no"
    profiles: ["default"]

  # --- Database Service ---
  db:
    image: postgres:17
    container_name: blog_db
    restart: always
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB__NAME}
      POSTGRES_USER: ${DB__USER}
      POSTGRES_PASSWORD: ${DB__PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${DB__USER} -d $${DB__NAME}"]
      interval: 10s
      timeout: 5s
      retries: 2
    profiles: ["default"]

  # --- Test Database Service ---
  test_db:
    image: postgres:17
    container_name: blog_test_db
    restart: always
    environment:
      POSTGRES_DB: test_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - test_postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d test_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    profiles: ["test"]

volumes:
  postgres_data:
  test_postgres_data:
